### ISSUE TITLE
order of connection_overrides entries is lost

### ISSUE THREAD

**Issue by anilbey** [BlueBrain/sonata-extension#22]
According to the sonata-extension docs the order of "connection_overrides" entries is important as it effects the simulation results [1]. 
As pointed out in here https://github.com/BlueBrain/snap/issues/181#issuecomment-1494196949 the json reader of libsonata is not preserving the insertion order which is the order scientists write the connection entries to the simulation config.

1. https://sonata-extension.readthedocs.io/en/latest/sonata_simulation.html

**Comment by joni-herttuainen** [comment]
I'll add that by [definition](https://www.json.org/json-en.html) JSON object (i.e., depicted by a `dict` in python) is
> an unordered set of name/value pairs

whereas an array (depicted by a `list` in python) is 
>an ordered collection of values

Therefore, the proposition for the fix would be to make the `connection_overrides` a `list` of `dict`s instead of the present collection of key-value pairs expected (by the spec) to be read in the order written in the file. If the name of the override (i.e., what is currently the `key`) is important, that should be added as a property for the override.

E.g., instead of current
```json
"connection_overrides": {
     "weaken_excitation": {
          "source": "Excitatory",
          "target": "Mosaic",
          "weight": 0.75,
          "spont_minis": 0.04
     },
     "deactivate_short_term_plasticity": {
          "source": "Mosaic",
          "target": "Mosaic",
          "synapse_configure": "%s.Fac = 0 %s.Dep = 0"
     }
}
```
we'd have:
```json
"connection_overrides": [
     {
          "name": "weaken_excitation"
          "source": "Excitatory",
          "target": "Mosaic",
          "weight": 0.75,
          "spont_minis": 0.04
     },
     {
          "name": "deactivate_short_term_plasticity",
          "source": "Mosaic",
          "target": "Mosaic",
          "synapse_configure": "%s.Fac = 0 %s.Dep = 0"
     }
]
```

**Comment by mgeplf** [comment]
Can you have a look at this @jamesgking / @pramodk ?  The simulation config is something that I defer to the simulation side of things.

**Comment by WeinaJi** [comment]
On neurodamus side (see [code](https://bbpgitlab.epfl.ch/hpc/sim/neurodamus-py/-/blob/main/neurodamus/io/sonata_config.py#L309)), we use the json decoder from python to read the connection dict keys (which seems to preserve the order), then to get each connection configuration via `libsonata.SimulationConfig`. That is probably the reason why we haven't noticed any difference between results from BlueConfig and from Sonata config.

About changing from `dict` to `list`, we will need to adapt neurodamus because dict keys will not exist. We also need to update the blueconfig-sonata converter. And, inform scientists who are already using the current format to update their files. I guess there are also changes needed in libsonata parser.

One question: why isn't [nlohmann::ordered_json](https://json.nlohmann.me/features/object_order/#alternative-behavior-preserve-insertion-order) preferred ? That will limit the changes only in libsonata.

**Comment by joni-herttuainen** [comment]
> why isn't [nlohmann::ordered_json](https://json.nlohmann.me/features/object_order/#alternative-behavior-preserve-insertion-order) preferred ? That will limit the changes only in libsonata.

That is a perfectly valid question. Using a list here is a safer option: continuing using `dict`, any tool that would use the format in the future, would need to take this design flaw into account and mitigate the issue. So it would be easier and safer in the long run to nip it in the bud. 

To turn the question 180 deg around: Why should we store data that needs to be ordered in a structure that by definition is unordered and have every tool to ever use the format to force keeping the ordering?

**Comment by WeinaJi** [comment]
@joni-herttuainen, thanks for clarifying. I agree with the point of fixing the data type at the origin. Yes, let's change to `list`.
